CREATE TABLE IF NOT EXISTS tenants (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

INSERT INTO tenants (name) VALUES ('Default') ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS todos (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  tenant_id INTEGER NOT NULL REFERENCES tenants(id),
  completed BOOLEAN NOT NULL DEFAULT FALSE,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  tenant_id INTEGER NOT NULL REFERENCES tenants(id),
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS profiles (
  id SERIAL PRIMARY KEY,
  bio TEXT,
  user_id INTEGER UNIQUE REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS users_todos (
  todo_id INTEGER REFERENCES todos(id),
  user_id INTEGER REFERENCES users(id),
  PRIMARY KEY (todo_id, user_id)
);
